#!/bin/sh
VENV_NAME="ci-turlo"
TMUX_SESSION_NAME="turlo"

source /usr/bin/virtualenvwrapper_lazy.sh
workon $VENV_NAME

tmux new-session -s $TMUX_SESSION_NAME -n vim -d
tmux new-window -n tests -t $TMUX_SESSION_NAME
tmux new-window -n hg -t $TMUX_SESSION_NAME
tmux new-window -n stuff -t $TMUX_SESSION_NAME
tmux new-window -n background_worker -t $TMUX_SESSION_NAME -t 8
tmux new-window -n turlo_run -t $TMUX_SESSION_NAME -t 9
tmux select-window -t $TMUX_SESSION_NAME:1

tmux send-keys -t $TMUX_SESSION_NAME:1 "workon $VENV_NAME; cd ..; clear" C-j
tmux send-keys -t $TMUX_SESSION_NAME:1 "vim" C-j
tmux send-keys -t $TMUX_SESSION_NAME:1 "gn" C-j

tmux send-keys -t $TMUX_SESSION_NAME:2 "workon $VENV_NAME; cd ../..; clear" C-j

tmux send-keys -t $TMUX_SESSION_NAME:3 "workon $VENV_NAME; clear" C-j

tmux send-keys -t $TMUX_SESSION_NAME:4 "workon $VENV_NAME; clear" C-j

tmux send-keys -t $TMUX_SESSION_NAME:8 "workon $VENV_NAME; clear" C-j
tmux send-keys -t $TMUX_SESSION_NAME:8 "turlo_background_worker debug" C-j

tmux send-keys -t $TMUX_SESSION_NAME:9 "workon $VENV_NAME; clear" C-j
tmux send-keys -t $TMUX_SESSION_NAME:9 "./manage.py turlo_run" C-j
