#!/bin/sh

alias ..='cd ..'
alias o='kde-open'
alias present='present -base=assets'
alias df='df -hPT'
alias du='du -ch'
alias grep="grep --exclude-dir=.git --exclude=.tags --exclude-dir=.coverage\
 --exclude-dir=.hg --exclude-dir=.ropeproject --exclude=tags\
 --color=auto --binary-files=without-match --no-messages\
 --exclude-dir=.git --exclude=.tags --exclude-dir=.coverage --exclude-dir=.hg\
 --exclude-dir=.ropeproject --exclude=tags"
alias fuck='sudo $(fc -ln -1)'

# systemd
alias poweroff='systemctl poweroff'
alias reboot='systemctl reboot'
alias suspend='systemctl suspend'
alias hibernate='systemctl hibernate'
alias suspend-hybrid='systemctl suspend-hybrid'

# tmux
alias tmux='tmux -u -2 -q'
alias ta='tmux attach'
alias tk='tmux kill-session -t'

# ls
alias ls='ls --color=auto'
alias ll='ls -alhF'
alias la='ls -A'
alias l='ls -CF'

# Run mutt from outside virtual environment
alias mutt='command -v deactivate >/dev/null 2>&1 && deactivate; mutt'

# Activate Python env
alias activate='source env/bin/activate'

# Ruby
alias be='bundle exec'

# Red-Green test runners
alias go-test='autocompile.py . .go "red-green go test ./..."'
alias django-test='autocompile.py . .py "red-green python manage.py test"'

if [[ -s $DOTFILES/sh/aliases.private ]]; then
    source $DOTFILES/sh/aliases.private
fi
