#!/bin/sh

alias ..='cd ..'
alias o='xdg-open'
alias df='df -hPT'
alias du='du -ch'
alias grep="grep --exclude-dir=.git --exclude=.tags --exclude-dir=.coverage\
 --exclude-dir=.hg --exclude-dir=.ropeproject --exclude=tags\
 --color=auto --binary-files=without-match --no-messages\
 --exclude-dir=.git --exclude=.tags --exclude-dir=.coverage --exclude-dir=.hg\
 --exclude-dir=.ropeproject --exclude=tags"
alias fuck='sudo $(fc -ln -1)'
alias copy='wl-copy -n'
alias upload="rsync --progress --recursive --filter=':- .gitignore' "
alias em='emacs -nw'
alias myip='curl -s https://zx2c4.com/ip | head -n1'

# tmux
alias tmux='tmux -u -2'
alias ta='tmux attach'
alias tk='tmux kill-session -t'

# ls
alias ls='ls --color=auto'
alias ll='ls -alhF'
alias la='ls -A'
alias l='ls -CF'

# Run mutt from outside virtual environment
alias mutt='command -v deactivate >/dev/null 2>&1 && deactivate; mutt'

# Activate Python env
alias activate='source env/bin/activate'

# Ruby
alias be='bundle exec'

# Red-Green test runners
alias go-test='autocompile.py . .go "red-green go test ./..."'
alias django-test='autocompile.py . .py "red-green python manage.py test"'

alias qrcode='qrencode -o - -t utf8'
