#!/bin/sh

alias ..='cd ..'
alias o='kde-open'
alias present='present -base=assets'
alias df='df -hPT'
alias du='du -ch'
alias grep='grep --exclude-dir=.git --exclude=.tags --exclude-dir=.coverage --exclude-dir=.hg'

# systemd
alias poweroff='systemctl poweroff'
alias reboot='systemctl reboot'
alias suspend='systemctl suspend'
alias hibernate='systemctl hibernate'
alias suspend-hybrid='systemctl suspend-hybrid'

# tmux
alias tmux='tmux -u -2 -q'
alias t='tmux'
alias ta='tmux attach'

# ls
alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Django (django-extensions and ipython required)
alias manage='python2 manage.py'
alias tests='manage test'
alias syncdb='manage syncdb'
alias dbshell='manage dbshell'
alias shellplus='manage shell_plus --ipython'
alias runserver='manage runserver 0.0.0.0:8000; stty sane'
alias runserver_plus='manage runserver_plus 0.0.0.0:8000; stty sane'
alias migrate='manage migrate'
alias genschema='manage schemamigration'
alias datamigration='manage datamigration'
alias collectstatic='manage collectstatic --noinput'
alias celery='manage celery worker --loglevel=info'

# Heroku
alias hmanage='heroku run python manage.py'
alias hcollectstatic='hmanage collectstatic --noinput'
alias hshellplus='hmanage shell_plus'
alias hlogs='heroku logs -t'
alias hdeploy='git hpush && hcollectstatic'

# Ruby
alias be='bundle exec'

# Red-Green test runners
alias go-test='autocompile.py . .go "red-green go test ./..."'
alias django-test='autocompile.py . .py "red-green python manage.py test"'

if [[ -s ./aliases.private ]]; then
    source ./aliases.private
fi
