#!/bin/zsh

autoload -U colors
colors
setopt prompt_subst

PROMPT='$(exit_code_prompt) '
RPROMPT='%{$fg_bold[%F{34}]%}$(virtualenv_prompt_info)%{$reset_color%} %{$fg_bold[%F{250}]%}%n:%F{240}%/ %F{240}$(vcprompt -f "[%n:%b%m]")%{$reset_color%} [%*%f]'
PROMPT_EOL_MARK=' ↴'
WORDCHARS=${WORDCHARS//[&=\/;\!#%\{]}

setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt APPEND_HISTORY
setopt EXTENDED_HISTORY
HISTFILE=~/.zsh_history
SAVEHIST=10000
HISTSIZE=10000

bindkey -e

# Bring back the Ctrl-x-e from bash
autoload edit-command-line
zle -N edit-command-line
bindkey '^[[3~' delete-char
bindkey '^Xe'   edit-command-line
