#!/bin/zsh

autoload -U colors
colors
setopt prompt_subst
setopt transient_rprompt

PROMPT='➔ '
RPROMPT='%{$fg[green]%}$(virtualenv_prompt_info) %{$fg[cyan]%}%/ %{$fg_bold[cyan]%}$(vcprompt -f "[%n:%b%m]")%{$reset_color%}'
WORDCHARS=${WORDCHARS//[&=\/;\!#%\{]}

setopt HIST_IGNORE_DUPS
setopt SHARE_HISTORY
setopt HIST_IGNORE_SPACE
setopt APPEND_HISTORY
setopt EXTENDED_HISTORY
HISTFILE=~/.zsh_history
SAVEHIST=10000
HISTSIZE=10000

# Prevents from accidentally overwriting an existing file
setopt NOCLOBBER


bindkey -e

# Bring back the Ctrl-x-e from bash
autoload edit-command-line
zle -N edit-command-line
bindkey '^Xe' edit-command-line
