#!/bin/zsh

source $DOTFILES/sh/funcs

function virtualenv_prompt_info() {
    if [ -n "$VIRTUAL_ENV" ]; then
        if [ -f "$VIRTUAL_ENV/__name__" ]; then
            local name=`cat $VIRTUAL_ENV/__name__`
        elif [ `basename $VIRTUAL_ENV` = "__" ]; then
            local name=$(basename $(dirname $VIRTUAL_ENV))
        else
            local name=$(basename $VIRTUAL_ENV)
        fi
        echo "($name)"
    fi
}

function exit_code_prompt() {
  local LAST_EXIT_CODE=$?
  if [[ $LAST_EXIT_CODE -eq 0 ]]; then
    EXIT_CODE_PROMPT="%{$fg_bold[green]%}-->%{$reset_color%}"
  else
    EXIT_CODE_PROMPT="%{$fg_bold[red]%}:$LAST_EXIT_CODE->%{$reset_color%}"
  fi
  echo "$EXIT_CODE_PROMPT"
}
