#!/bin/zsh

source $DOTFILES/sh/funcs

function exit_code_prompt() {
  local LAST_EXIT_CODE=$?
  if [[ $LAST_EXIT_CODE -eq 0 ]]; then
    EXIT_CODE_PROMPT="%{$fg_bold[green]%}-->%{$reset_color%}"
  else
    EXIT_CODE_PROMPT="%{$fg_bold[red]%}:$LAST_EXIT_CODE->%{$reset_color%}"
  fi
  echo "$EXIT_CODE_PROMPT"
}
