#!/bin/zsh
[[ $- != *i* ]] && return

stty -ixon

source $DOTFILES/sh/environment
source $DOTFILES/sh/aliases
source $DOTFILES/zsh/funcs
source $DOTFILES/zsh/config
source $DOTFILES/zsh/completion

if [[ -s /usr/bin/virtualenvwrapper_lazy.sh ]]; then
    source /usr/bin/virtualenvwrapper_lazy.sh
fi
