#!/bin/bash

alias tmux='tmux -u -2'

alias t='tmux'
alias ta='tmux attach'

# virtualenv
alias vv='source ./env/bin/activate'
alias vvv='source ../env/bin/activate'

# ls
alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Clever, right?
alias су='su'
alias please='/usr/bin/sudo'

# Django (django-extensions and ipython required)
alias manage='python2 manage.py'
alias tests='manage test'
alias syncdb='manage syncdb'
alias dbshell='manage dbshell'
alias shellplus='manage shell_plus --ipython'
alias runserver='manage runserver_plus 0.0.0.0:8000'
alias runserver_plain='manage runserver 0.0.0.0:8000'
alias migrate='manage migrate'
alias genschema='manage schemamigration'
alias collectstatic='manage collectstatic -l --noinput'

alias ..='cd ..'
alias o='kde-open'
