#!/bin/bash

alias tmux='tmux -u -2 -q'

alias t='tmux'
alias ta='tmux attach'

# ls
alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Clever, right?
alias су='su'

# Django (django-extensions and ipython required)
alias manage='python2 manage.py'
alias tests='manage test'
alias syncdb='manage syncdb'
alias dbshell='manage dbshell'
alias shellplus='manage shell_plus --ipython'
alias runserver='manage clean_pyc; manage runserver_plus 0.0.0.0:8000'
alias runserver_plain='manage runserver 0.0.0.0:8000'
alias migrate='manage migrate'
alias genschema='manage schemamigration'
alias datamigration='manage datamigration'
alias collectstatic='manage collectstatic --noinput'
alias celery='manage celery worker --loglevel=info'

# Heroku
alias hmanage='heroku run python manage.py'
alias hcollectstatic='hmanage collectstatic --noinput'
alias hshellplus='hmanage shell_plus'
alias hlogs='heroku logs -t'
alias hdeploy='git hpush && hcollectstatic'

alias ..='cd ..'
alias o='kde-open'

alias go-test='autocompile.py . .go go-red-green'
