#!/bin/bash
test -r "$HOME/.config/user-dirs.dirs" && source "$HOME/.config/user-dirs.dirs"
test -r "$HOME/.dir_colors"            && eval $(dircolors "$HOME/.dir_colors")
test -r "$HOME/.bashrc"                && source "$HOME/.bashrc"
