#!/bin/bash
[[ $- != *i* ]] && return

stty -ixon

source $HOME/dotfiles/sh/aliases
source $HOME/dotfiles/bash/config
source $HOME/dotfiles/sh/environment
source $HOME/dotfiles/sh/funcs
source $HOME/dotfiles/bash/completion

PS1='\W $(vcprompt -f "[%n:%b%m]")> '
