#!/bin/bash
[[ $- != *i* ]] && return

stty -ixon

source $DOTFILES/sh/aliases
source $DOTFILES/bash/config
source $DOTFILES/sh/environment
source $DOTFILES/sh/funcs
source $DOTFILES/bash/completion

PS1='\W $(vcprompt -f "[%n:%b%m]")> '
